
services:
  dongguatv:
    build: .
    container_name: dongguatv
    restart: unless-stopped
    ports:
    - "3010:3010"
    environment:
    - PORT=3010
    - TMDB_API_KEY=key
    - ADMIN_PASSWORD=admin
    volumes:
    - ./db.json:/app/db.json
